
 *
 * iass|intelligent autonomous systems studio
 *
 * iass component: designer
 *  

  ================== DEPENDENCIES ================== 

  * GTKmm, Glademm
 * orbsvcs
 change line 43 of /usr/include/orbsvcs/orbsvcs/CosNamingC.h 
 - #include "orbsvcs/Naming/naming_export.h"
 + #include "Naming/naming_export.h"

 * libiass
 * iass_simulations_server

